version: '3.8'

services:
  api:
    build: api
    container_name: api
    ports:
      - 3000:3000
    command: npx json-server --watch db.json --host 0.0.0.0

  web:
    build: 
      context: spacedkts
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 80:8000
    links:
      - api
    command: symfony server:start --no-tls --port 8000
