<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSbHxJBK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSbHxJBK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSbHxJBK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSbHxJBK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSbHxJBK\App_KernelDevDebugContainer([
    'container.build_hash' => 'SbHxJBK',
    'container.build_id' => 'cd0fc972',
    'container.build_time' => 1673798462,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSbHxJBK');
