<?php

namespace ContainerFmExzb9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpaceshipControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SpaceshipController' shared autowired service.
     *
     * @return \App\Controller\SpaceshipController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'SpaceshipController.php';

        $container->services['App\\Controller\\SpaceshipController'] = $instance = new \App\Controller\SpaceshipController(($container->privates['App\\Helper\\ClientHelper'] ?? $container->load('getClientHelperService')));

        $instance->setContainer(($container->privates['.service_locator.y88jt_Q'] ?? $container->load('get_ServiceLocator_Y88jtQService'))->withContext('App\\Controller\\SpaceshipController', $container));

        return $instance;
    }
}
